- platform: generic
  still_image_url: http://api.sat24.com/animated/EU/rainTMC/3/Central%20Europe%20Standard%20Time/3272411 
  name: Radarovy zaznam Evropy
  
- platform: generic
  name: ISS
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}&zoom=3&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}
  limit_refetch_to_url_change: true
  
- platform: generic
  name: ISS2
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}&zoom=5&size=500x500&maptype=roadmap&markers=color:red%7Clabel:ISS%7C{{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}
  limit_refetch_to_url_change: true